"""equity snapshots

Revision ID: 725c8bc1940a
Revises: 57aa7175ab20
Create Date: 2026-06-04 16:43:56.586210

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (referenced by some autogenerated JSONB(astext_type=Text()) columns)


revision: str = '725c8bc1940a'
down_revision: str | None = '57aa7175ab20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equity_snapshots_strategy_id'), 'equity_snapshots', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equity_snapshots_strategy_id'), table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    # ### end Alembic commands ###
