"""regime models and regimes

Revision ID: 918a71797f7c
Revises: 66f3e7f60c8f
Create Date: 2026-06-04 16:22:07.567814

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (referenced by some autogenerated JSONB(astext_type=Text()) columns)
from sqlalchemy.dialects import postgresql

revision: str = '918a71797f7c'
down_revision: str | None = '66f3e7f60c8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regime_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('n_components', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_models_symbol'), 'regime_models', ['symbol'], unique=False)
    op.create_table('regimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('label', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('unstable', sa.Boolean(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['regime_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'ts', name='uq_regime_symbol_ts')
    )
    op.create_index(op.f('ix_regimes_symbol'), 'regimes', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regimes_symbol'), table_name='regimes')
    op.drop_table('regimes')
    op.drop_index(op.f('ix_regime_models_symbol'), table_name='regime_models')
    op.drop_table('regime_models')
    # ### end Alembic commands ###
