"""alerts

Revision ID: b7c1a2d3e4f5
Revises: dfa9b5d80182
Create Date: 2026-06-04 18:00:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (referenced by autogenerated JSONB(astext_type=Text()))
from sqlalchemy.dialects import postgresql

revision: str = 'b7c1a2d3e4f5'
down_revision: str | None = 'dfa9b5d80182'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'level',
            sa.Enum('info', 'warning', 'critical', name='alertlevel', native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column('category', sa.String(length=32), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column(
            'detail',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
        ),
        sa.Column('delivered', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('(CURRENT_TIMESTAMP)'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_alerts_category'), 'alerts', ['category'], unique=False)
    op.create_index(op.f('ix_alerts_level'), 'alerts', ['level'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_alerts_category'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_level'), table_name='alerts')
    op.drop_table('alerts')
