"""execution orders fills positions

Revision ID: c21051da23ec
Revises: fd38e0d3efff
Create Date: 2026-06-04 16:33:32.279622

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (referenced by some autogenerated JSONB(astext_type=Text()) columns)


revision: str = 'c21051da23ec'
down_revision: str | None = 'fd38e0d3efff'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.Enum('buy', 'sell', name='orderside', native_enum=False, length=8), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'filled', 'canceled', 'rejected', name='orderstatus', native_enum=False, length=12), nullable=False),
    sa.Column('executor', sa.String(length=8), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('executor', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'symbol', 'executor', name='uq_position_strat_sym_exec')
    )
    op.create_index(op.f('ix_positions_strategy_id'), 'positions', ['strategy_id'], unique=False)
    op.create_table('sim_wallets',
    sa.Column('strategy_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('strategy_id')
    )
    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_index(op.f('ix_fills_strategy_id'), 'fills', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fills_strategy_id'), table_name='fills')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_table('sim_wallets')
    op.drop_index(op.f('ix_positions_strategy_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
