"""proposals and token usage

Revision ID: dfa9b5d80182
Revises: 725c8bc1940a
Create Date: 2026-06-04 16:48:39.082489

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (referenced by some autogenerated JSONB(astext_type=Text()) columns)
from sqlalchemy.dialects import postgresql

revision: str = 'dfa9b5d80182'
down_revision: str | None = '725c8bc1940a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('feedback', 'llm', 'user', name='proposalsource', native_enum=False, length=12), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='proposalstatus', native_enum=False, length=12), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('proposed_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_strategy_id'), 'proposals', ['strategy_id'], unique=False)
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_usage_strategy_id'), 'token_usage', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_usage_strategy_id'), table_name='token_usage')
    op.drop_table('token_usage')
    op.drop_index(op.f('ix_proposals_strategy_id'), table_name='proposals')
    op.drop_table('proposals')
    # ### end Alembic commands ###
