"""risk events

Revision ID: fd38e0d3efff
Revises: e08b41212e8b
Create Date: 2026-06-04 16:29:25.380925

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (referenced by some autogenerated JSONB(astext_type=Text()) columns)
from sqlalchemy.dialects import postgresql

revision: str = 'fd38e0d3efff'
down_revision: str | None = 'e08b41212e8b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('account', 'strategy', name='riskscope', native_enum=False, length=16), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_strategy_id'), 'risk_events', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_events_strategy_id'), table_name='risk_events')
    op.drop_table('risk_events')
    # ### end Alembic commands ###
